### ISSUE TITLE
Page do not fit in mobile screen

### ISSUE THREAD

**Issue by richsergsam** [kosdmit/CV_project#1]
If you open site from mobile device you can scroll page horizontally.

**Comment by richsergsam** [comment]
There are several elements which are not fit on mobile screens because of width of the div container.
<img width="738" alt="image" src="https://github.com/kosdmit/CV_project/assets/18329682/9cf13584-ae3e-4edc-a99c-d31446407467">

**Comment by richsergsam** [comment]
@kosdmit I used this js code to find it:
`var docWidth = document.documentElement.offsetWidth;
[].forEach.call(
  document.querySelectorAll('*'),
  function(el) {
    if (el.offsetWidth > docWidth) {
      console.log(el);
    }
  }
);`
Sorce: https://support.google.com/webmasters/thread/16952863?hl=en&msgid=16955701

**Comment by kosdmit** [comment]
Fixed. Thank you for usefull link.
