### ISSUE TITLE
Repeat password 

### ISSUE THREAD

**Issue by richsergsam** [kosdmit/CV_project#5]
Make repeat password input js validation to compare first and second password inputs.

**Comment by kosdmit** [comment]
Done!

**Comment by richsergsam** [comment]
There are still no error messages or any information when I try to use different password for repeat password input.
How reproduce the issue:
<img width="362" alt="image" src="https://github.com/kosdmit/CV_project/assets/18329682/2dd3c348-42aa-4a70-91ba-826e93e104fb">
Please reopen the issue

**Comment by kosdmit** [comment]
update is deployed now
