### ISSUE TITLE
HTTPS, CORS

### ISSUE THREAD

**Issue by richsergsam** [kosdmit/CV_project#7]
<img width="514" alt="image" src="https://github.com/kosdmit/CV_project/assets/18329682/fcb84281-dcbf-4227-8c08-8830f186c551">

There is error in console which may be connected to lack of ssl certificate

**Comment by kosdmit** [comment]
Server has been configurated for working with ssl certificate

**Comment by richsergsam** [comment]
@kosdmit it will be better if you configure redirect from http to https
<img width="246" alt="image" src="https://github.com/kosdmit/CV_project/assets/18329682/e15d5f0a-2de8-4ecb-9808-b23167ab9a8e">

**Comment by kosdmit** [comment]
redirect has been configurated
